server:
  port: 9000

spring:
  application:
    name: auth
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
