server:
  port: 6000

spring:
  application:
    name: analytics
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/popug-analytics
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30_000
      maximum-pool-size: 50
      minimum-idle: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      register-mbeans: true
  liquibase:
    change-log: classpath:/migrations/changelog-master.xml
  data:
    web:
      pageable:
        one-indexed-parameters: true

  kafka:
    consumer:
      group-id: analytics
      bootstrap-servers: http://localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: "*"
