server:
  port: 3000

spring:
  application:
    name: task-tracker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

management:
  endpoints:
    web:
      exposure:
        include: "*"
