server:
  port: 3000

spring:
  application:
    name: task-tracker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/popug-task-tracker
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30_000
      maximum-pool-size: 50
      minimum-idle: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      register-mbeans: true
  liquibase:
    change-log: classpath:/migrations/changelog-master.xml
  data:
    web:
      pageable:
        one-indexed-parameters: true

  cloud:
    function:
      definition: userModified
    stream:
      bindings:
        streamingUser-in-0:
          destination: Streaming-User
          content-type: application/json
          group: taskTracker
        taskLifecycle:
          destination: TaskLifeCycle
          content-type: application/json
      kafka:
        binder:
          brokers: localhost
          zkNodes: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
